[tools]
k3d = "latest"
k9s = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'devops-study-app'
GITOPS_REPO = 'devops-study-app-gitops'

[hooks]
enter = "bash ./scripts/setup_project"

[tasks.k8s-setup-local]
description = "Set up a Kubernetes cluster that builds the local images and applies them"
run = "bash ./kubernetes/setup_cluster_local"

[tasks.k8s-setup-minimal]
description = "Set up a minimal Kubernetes cluster for testing. Does not apply anything."
run = "bash ./kubernetes/setup_cluster_minimal"

[tasks.e2e-test]
description = "Run end-to-end tests on the Kubernetes deployment"
run = "cd ./kubernetes && uv run e2e_test.py"
